services:
  mongodb:
    image: mongo:8.0.4-noble
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1GB
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  mongodb_data:
