[project]
name = "django-mongo"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.4, <6.0",
    "python-dotenv>=1.0.1",
]

[dependency-groups]
lint = [
    "ruff>=0.8.6",
]
